### ISSUE TITLE
[FEAT] Aur package?

### ISSUE THREAD

**Issue by WafiWadud** [aartaka/pretty.c#1]
Could i make an aur package for this? (so that I can install it globally)

**Comment by aartaka** [comment]
Sure! Need any help from my side?

**Comment by WafiWadud** [comment]
what should the url for this be?

**Comment by WafiWadud** [comment]
I'm doing your github for now

**Comment by WafiWadud** [comment]
gonna send a pull request. i need you to accept it before I can upload this thing to the aur
