### ISSUE TITLE
"with" parameter order  confusing

### ISSUE THREAD

**Issue by eyalroz** [aartaka/pretty.c#4]
The "with" construct shouldn't first take the destructing expression. As text, it would be:

> With variable var, constructed with expression e1, destructed with expression e2 ...

so, in code, something like:
```
#define with(var, constructing_expr, destructing_expr)
```
rather than
```
#define with(destructing_expr, var, constructing_expr)
```

**Comment by aartaka** [comment]
Eyal Rozenberg ***@***.***> writes:

> The "with" construct shouldn't first take the destructing expression. As text, it would be:
>
>  With variable var, constructed with expression e1, destructed with expression e2 ...
>
> so, in code, something like:
>
> #define with(var, constructing_expr, destructing_expr)
>
> rather than
>
> #define with(destructing_expr, var, constructing_expr)

This would be quite hard to do with C macros, but I've heard you. Now
it's with(var, destructor, ...) in 63d13c407d985076fcde3afa723250a3a4e18ba5

**Comment by eyalroz** [comment]
Better. I guess I'll close this.
